### ISSUE TITLE
Set nicknames after installation

### ISSUE THREAD

**Issue by seancolsen** [ginkgostreet/com.ginkgostreet.nickfix#1]
The README [recommends](https://github.com/ginkgostreet/com.ginkgostreet.nickfix/blob/243c706ec11ee4f289edb9d4ef687ab0ea6d7259/README#L5) that a query be run after installation to set the nicknames. I think this extension should automatically run this query after installation, especially if this extension is to be approved for installation through the CiviCRM UI because users will not see the README file and thus likely expect contacts to have set nicknames after installing the extension.

**Comment by universalhandle** [comment]
Hmmm... it would be trivial to do this. If we did I think the extension notes (the ones that show up in the UI should very clearly declare that simply installing this extension will irreversibly change your contact records. A less... drastic?... way to do this would be to make it a scheduled job... or to build a screen with a button on it so users have to take explicit action before updating all contacts.

Am I too conservative?

**Comment by seancolsen** [comment]
I like the scheduled-job and screen-with-button approaches too, as long as the extension makes it clear to the user that this additional step is necessary after installing. I don't think it's too conservative.

**Comment by seancolsen** [comment]
Here's another idea which I think is medium-conservative. When uninstalling, do the following: 

```sql
UPDATE civicrm_contact
SET nick_name = NULL
WHERE 
  nick_name = first_name AND 
  contact_type = 'Individual'
```

Granted, the DB would still be altered after install-uninstall, but only for any contacts that previously had `nick_name = first_name`, which should be uncommon I think.
